on: [push, workflow_dispatch]
name: Build and Publish Image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          ./gradlew assemble
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          
      - name: 'Deploy to Azure Container App'
        uses: 'azure/container-apps-deploy-action@v0'
        with:
          acrName: ivettmyapp
          containerAppName: myapp
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          imageToDeploy: ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}