on: [push, workflow_dispatch]
name: Build and Publish Image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          ./gradlew assemble
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myapp -g DefaultResourceGroup-EUS --server ${{ secrets.ACR_ENDPOINT }} --username  ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
            az containerapp update -n myapp -g DefaultResourceGroup-EUS --image ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}