on: [push]
name: Build and Publish Image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          ./gradlew assemble
          docker build . -t ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          docker push ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          
      - name: 'Deploy to Azure Container App'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
          image: ${{ secrets.ACR_ENDPOINT }}/myapp:${{ github.sha }}
          registry-login-server: ${{ secrets.ACR_ENDPOINT }}
          registry-username: ${{ secrets.ACR_USERNAME }}
          registry-password: ${{ secrets.ACR_PASSWORD }}
          name: myapp
          location: 'east us'